### ISSUE TITLE
activating a route rule on a linux X11 machine breaks Desktop remote control

### ISSUE THREAD

**Issue by guerby** [ryanblenis/MeshCentral-RoutePlus#10] opened 2020-05-07 08:02 UTC
Choosing Set on a linux X11 machine then adding a route rule (any) will make Connect in Desktop no longer work (turn to disconnect immediately). Removing the rule and restarting the agent will make Desktop Connect work again.

meshcentral 0.5.25

**Comment by ryanblenis** [comment] 2020-05-07 08:14
Interesting, what distro are you using so I can build a test VM for this case?

**Comment by guerby** [comment] 2020-05-07 09:07
debian 10.3 with /etc/gdm3/daemon.conf

```
[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false
```

Same system than for this bug report :

https://github.com/Ylianst/MeshCentral/issues/1287

gdm3 is running X but the meshagent doesn't seem to be able to pick up the login screen

Thanks!

**Comment by guerby** [comment] 2020-05-07 09:19
@ryanblenis I know how to recompile the linux meshagent if needed

**Comment by guerby** [comment] 2020-05-07 10:42
And of I forgot : the machine was running a GNOME/X11 session of a logged in user.

**Comment by ryanblenis** [comment] 2020-05-07 17:56
Thanks, I'll install a VM with Debian 10.3 on it and give it a test. The plugin doesn't require a recompile of the MeshAgent (it's all in the MeshCore / aka Javascript). If it did require a recompile we'd likely be involving Brian from the MeshAgent project because it would be a root cause of the agent functionality itself, and not the plugin.

**Comment by ryanblenis** [comment] 2020-05-07 18:18
Ok, so I 
1. installed a fresh copy from https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-10.3.0-amd64-netinst.iso.torrent ran the default install
2. set WaylandEnable=false in /etc/gdm3/daemon.conf
3. Rebooted, installed MeshAgent (left logged into X session as user for the remainder of the test)
4. Set the debian PC as "My Computer" in RoutePlus
5. Added a route to another node
6. Was still able to remote desktop in via MeshCentral without issue.

Just want to make sure those are the repeatable steps to take to try to reproduce the issue... because I'm not seeing it on my end. Let me know if I missed something.

**Comment by guerby** [comment] 2020-05-07 19:48
I tried again (cleanup/reboot/reinstall) and I got sometimes Desktop working and sometimes not but not depending on RoutePlus additions as for my first tests.

In the webagent console after my experiments I noticed ("versions" I explicitely typed it):

```
ncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
Error trying to determine XAUTHORITY/DISPLAY: TypeError: undefined not callable (property 'trim' of [object Function]) 
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'userid' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'Command' on 'MeshAgent' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'handleServerCommand()'
> versions
{
  "openssl": "1.1.1g",
  "duktape": "v2.3.0",
  "meshAgent": "2020-04-26T23:39:59.000Z"
}
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: cannot read property 'userid' of undefined in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'write' of [object Object]) in method 'onTunnelData()'
uncaughtException1: Error:  => EventEmitter.emit(): Event dispatch for 'data' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable 

```
(long list of the last one if I go back to Desktop and do something)

For reference I have 3 plugins installed enabled in meshcentral Event Log 0.0.23, Script Task 0.0.15 and RoutePlus 0.1.3.

I will probably reinstall the server and all the agents in the next few days, feel free to close if you don't think issues are related to routeplus.

Sorry for the noise.

**Comment by ryanblenis** [comment] 2020-05-07 21:02
Sorry, just want to confirm (probably a language or syntax) that you tested without plugins and have the same issues. In that case, we can close this as it is more than likely unrelated to the plugin.

**Closed** 2020-05-09 04:52 UTC
